services:
  postgres:
    container_name: example-docker-compose-postgresql
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=docker-compose-example'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=postgres'
    ports:
      - '1453:5432'
    expose:
      - '1453'
  redis:
    container_name: example-docker-compose-redis-cache
    image: 'redis:latest'
    ports:
      - '1923:6379'
    expose:
      - '1923'